### ISSUE TITLE
Automerge is updating a PR that is not passing tests

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/automerge#3]
Here we have a PR: https://github.com/runtimeverification/evm-semantics/pull/2321

It is approved, but not passing tests. But the automerger keeps pressing teh "Update Brnach" button, which is wasting CI time.

**Comment by FWBlueWizard** [comment]
Fixed now in v1.0.3 results of issue fix tested against the automerger-test are [here](https://github.com/runtimeverification/automerge/actions/runs/8305365838)
